In [1]:
%pip install numpy pandas


[notice] A new release of pip is available: 25.3 -> 26.2.1
[notice] To update, run: pip3 install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

In [3]:
import pandas as pd

In [4]:
print("NumPy and pandas imported successfully!")

NumPy and pandas imported successfully!


In [5]:
import numpy as np
import pandas as pd

# ============================================================
# 1. ONE-DIMENSIONAL ARRAY
# ============================================================

print("=" * 60)
print("1. ONE-DIMENSIONAL ARRAY")
print("=" * 60)

arr = np.array([10, 20, 30, 40, 50, 60, 70])

print("Original Array:", arr)

# Indexing
print("\n--- Indexing Operations ---")
print("First Element:", arr[0])
print("Last Element:", arr[-1])
print("Third Element:", arr[2])
print("Second Last Element:", arr[-2])

# Slicing
print("\n--- Slicing Operations ---")
print("Elements from Index 1 to 4:", arr[1:5])
print("First Three Elements:", arr[:3])
print("Elements from Index 2:", arr[2:])
print("Every Second Element:", arr[::2])
print("Every Third Element:", arr[::3])
print("Reversed Array:", arr[::-1])
print("Index 1 to 5 with Step 2:", arr[1:6:2])

# ============================================================
# 2. TWO-DIMENSIONAL ARRAY
# ============================================================

print("\n" + "=" * 60)
print("2. TWO-DIMENSIONAL ARRAY")
print("=" * 60)

arr2 = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

print("Original 2D Array:\n", arr2)

# Indexing
print("\n--- 2D Indexing Operations ---")
print("First Row:", arr2[0])
print("First Element:", arr2[0, 0])
print("Element at Row 2, Column 3:", arr2[1, 2])
print("Last Element:", arr2[-1, -1])

# Slicing
print("\n--- 2D Slicing Operations ---")
print("First Two Rows:\n", arr2[:2])
print("First Two Columns:\n", arr2[:, :2])
print("First Two Rows and Columns:\n", arr2[:2, :2])
print("Every Second Row:\n", arr2[::2])
print("Every Second Column:\n", arr2[:, ::2])
print("Reversed Rows:\n", arr2[::-1])
print("Reversed Columns:\n", arr2[:, ::-1])

# ============================================================
# 3. NUMPY OPERATIONS
# ============================================================

print("\n" + "=" * 60)
print("3. NUMPY OPERATIONS")
print("=" * 60)

print("Sum of All Elements:", np.sum(arr2))
print("Sum of Each Row:", np.sum(arr2, axis=1))
print("Sum of Each Column:", np.sum(arr2, axis=0))
print("Mean:", np.mean(arr2))
print("Maximum:", np.max(arr2))
print("Minimum:", np.min(arr2))
print("Standard Deviation:", np.std(arr2))
print("Transpose:\n", arr2.T)

# ============================================================
# 4. PANDAS DATAFRAME
# ============================================================

print("\n" + "=" * 60)
print("4. PANDAS DATAFRAME")
print("=" * 60)

data = {
    "Name": ["Asha", "Bhavya", "Chhavi", "Diya"],
    "Age": [19, 20, 19, 21],
    "Marks": [85, 92, 78, 95],
    "Department": ["AI&ML", "CSE", "AI&ML", "ISE"]
}

df = pd.DataFrame(data)

print("Original DataFrame:")
print(df)

# Pandas indexing
print("\n--- Pandas Indexing Operations ---")
print("First Five Rows:\n", df.head())
print("Last Two Rows:\n", df.tail(2))
print("Name Column:\n", df["Name"])
print("First Two Rows:\n", df.iloc[:2])
print("First Two Columns:\n", df.iloc[:, :2])
print("Student at Row 1, Column 2:", df.iloc[1, 2])

# Filtering and statistical operations
print("\n--- Pandas Filtering and Operations ---")
print("Students with Marks Greater Than 80:")
print(df[df["Marks"] > 80])

print("Average Marks:", df["Marks"].mean())
print("Highest Marks:", df["Marks"].max())
print("Lowest Marks:", df["Marks"].min())

print("\nDataFrame Sorted by Marks:")
print(df.sort_values(by="Marks", ascending=False))

# ============================================================
# 6. FINAL DATAFRAME OPERATIONS
# ============================================================

print("\n" + "=" * 60)
print("6. FINAL DATAFRAME OPERATIONS")
print("=" * 60)

print("DataFrame Information:")
df.info()

print("\nStatistical Summary:")
print(df.describe())

print("\nColumn Names:")
print(df.columns)

print("\nDataFrame Shape:")
print(df.shape)


1. ONE-DIMENSIONAL ARRAY
Original Array: [10 20 30 40 50 60 70]

--- Indexing Operations ---
First Element: 10
Last Element: 70
Third Element: 30
Second Last Element: 60

--- Slicing Operations ---
Elements from Index 1 to 4: [20 30 40 50]
First Three Elements: [10 20 30]
Elements from Index 2: [30 40 50 60 70]
Every Second Element: [10 30 50 70]
Every Third Element: [10 40 70]
Reversed Array: [70 60 50 40 30 20 10]
Index 1 to 5 with Step 2: [20 40 60]

2. TWO-DIMENSIONAL ARRAY
Original 2D Array:
 [[10 20 30]
 [40 50 60]
 [70 80 90]]

--- 2D Indexing Operations ---
First Row: [10 20 30]
First Element: 10
Element at Row 2, Column 3: 60
Last Element: 90

--- 2D Slicing Operations ---
First Two Rows:
 [[10 20 30]
 [40 50 60]]
First Two Columns:
 [[10 20]
 [40 50]
 [70 80]]
First Two Rows and Columns:
 [[10 20]
 [40 50]]
Every Second Row:
 [[10 20 30]
 [70 80 90]]
Every Second Column:
 [[10 30]
 [40 60]
 [70 90]]
Reversed Rows:
 [[70 80 90]
 [40 50 60]
 [10 20 30]]
Reversed Columns:
 [[30 